### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by theohmwoa** [theophilushmwo/OrthancGif#8]
La mozaic ne se s'affiche pas bien sur Orthanc mais bien en local

**Comment by salimkanoun** [comment]
montre en screenshot le probleme ?

**Comment by theohmwoa** [comment]
<img width="45" alt="image" src="https://user-images.githubusercontent.com/83962803/181733353-f2eaad61-b7cc-4dd0-a09e-ad593dfc8e1c.png">
